before_install:
  - "sudo apt-get update"
  - "sudo apt-get install --no-install-recommends texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra latex-xcolor"
script:
  - pdflatex cv.tex
deploy:
  provider: releases
  api_key:
    secure: "testfornow"
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true