before_install:
  - "apt-get update && apt-get install build-essential texlive-full"
script:
  - pdflatex cv.tex
deploy:
  provider: releases
  api_key:
    secure: "testfornow"
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true