if: tag IS present
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install --no-install-recommends texlive-full"
script:
  - pdflatex cv.tex
deploy:
  provider: releases
  file:
    - cv.pdf
  api_key:
    secure: "MY_API_KEY"
  skip_cleanup: true
