before_install:
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended latex-xcolor dvipng"
script:
  - pdflatex cv.tex
deploy:
  provider: releases
  api_key:
    secure: "testfornow"
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true