before_install:
  - "sudo apt-get update"
  - "sudo apt-get install --no-install-recommends texlive-latex-full"
script:
  - pdflatex cv.tex
  - cat cv.log
deploy:
  provider: releases
  api_key:
    secure: "testfornow"
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true