before_install:
  - "sudo apt-get update && sudo apt-get install texlive"
script:
  - pdflatex cv.tex
deploy:
  provider: releases
  api_key:
    secure: "testfornow"
  file:
    - cv.pdf
  skip_cleanup: true
  on:
    tags: true